### PR TITLE
Some corrections to the translation for words "key" and "Entity"

### PR DESCRIPTION
**Pull request by swarad07**
- "Entity" should be written as **एंटिटी**, it is more correct then **संस्था**.
(Ref: https://localize.drupal.org/translate/languages/mr/translate?page=7&project=drupal&status=2&release=477603&search=&author=&context=all&limit=10&sid=0)
- Correcting the translation for "**key**".

### CODE REVIEW

**Comment by enzolutions** [comment]
Hi @swarad07 

Due to some changes this PR is not possible to be merged in master, could you resolve the conflict and push the changes again.

Thanks

**Comment by swarad07** [comment]
Yup, let me do that.

**Comment by swarad07** [comment]
Hi @enzolutions, can you check now. There should not be any conflicts.

**Comment by enzolutions** [comment]
Thank you @swarad07

**Pull request merged**
